@startuml
start
:User executes add contact command;
:MyCRM parses user inputs;
if() then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful adding contact message on UI;
else ([Valid Input])
    fork
    :Creates new **Name**;
    fork again
    :(Optional)
    Creates new **Phone**;
    fork again
    : (Optional)
    Creates new **Email**;
    fork again
    : (Optional)
    Creates new **Address**;
    end fork
    :Creates new contact;
    if () then ([Duplicate contact])
      :Throws CommandException;
      :Displays unsuccessful adding contact message on UI;
    else ([Else])
    :Stores contact into MyCRM;
    :Displays successful adding contact message on UI;
    endif
endif;
stop
@enduml
