@startuml
start
:User executes add contact command;
:MyCRM parses user inputs;
if() then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful add contact Message on UI;
else ([Valid Input])
    fork
    :Creates new **Name**;
    fork again
    :(Optional)
    Creates new **Phone**;
    fork again
    : (Optional)
    Creates new **Email**;
    fork again
    : (Optional)
    Creates new **Address**;
    end fork
    if () then ([Duplicate contact])
            :Throws CommandException;
            :Displays unsuccessful adding contact on UI;
        else ([Else])
    :Creates new contact;
    :Stores contact into MyCRM;
    :Displays successful add contact Message on UI;
    endif
endif;
stop
@enduml
