@startuml
start
:User executes delete contact command;
:MyCRM parses user inputs;
if () then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful deleting contact message on UI;
else ([Valid Input])
if () then ([Invalid Index])
    :Throws CommandException;
    :Displays unsuccessful deleting contact message on UI;
else ([Else])
    :Gets contact to be deleted with index provided;
    if () then ([Contact not linked to any jobs])
    :Delete the specific contact from MyCRM;
    :Displays successful deleting contact message on UI;
    else ([Contact linked to a job]))
    :Throws CommandException;
    :Displays unsuccessful deleting contact message on UI;
endif
endif
endif
stop
@enduml
