@startuml
start
:User executes edit contact command;
:MyCRM parses user inputs;
if () then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful editing contact message on UI;
else ([Valid Input])
if () then ([Invalid Index])
    :Throws CommandException;
    :Displays unsuccessful editing contact on UI;
else ([Else])
:Gets contact to be edited with index provided;
:Creates edited contact;
if () then ([Duplicate Contact])
    :Throws CommandException;
    :Displays unsuccessful editing contact on UI;
else ([Else])
:Replaces specific contact with edited contact;
:Displays successful editing contact message on UI;
endif
endif
endif
stop
@enduml
