@startuml
start
:User executes edit contact command;
:MyCRM parses user inputs;
if () then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful edit contact Message on UI;
else ([Valid Input])
:Gets contact to be edited with index provided;
:Creates edited contact;
:Replaces specific contact with edited contact;
:Displays successful editing contact message on UI;
endif
stop
@enduml
