@startuml
start
:User executes add contact command;
:MyCRM parses user inputs;
while () is ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful add contact Message on UI;
endwhile ([Valid Input])
:Gets contact to be edited with index provided;
:Creates edited contact;
:Replaces specific contact with edited contact;
:Displays successful edited contact on UI;
stop
@enduml
