@startuml
start
:User executes find contact command;
:MyCRM parses user inputs;
if () then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful finding contact message on UI;
else ([Valid Input])
:Gets contact names predicate with keywords provided;
:Update contact list with new predicate:
showing contacts whose names contain keywords;
:Displays successful finding contact message on UI;
endif
stop
@enduml
