@startuml
start
:User executes hide contact command;
:MyCRM parses user inputs;
if () then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful hiding contact message on UI;
else ([Valid Input])
if () then ([Invalid Index])
    :Throws CommandException;
    :Displays unsuccessful hiding contact on UI;
else ([Else])
:Gets contact to be hidden with index provided;
if () then ([Contact is not hidden])
:Hide the specific contact from MyCRM;
:Displays successful hiding contact message on UI;
else ([Contact is hidden])
:Throws CommandException;
:Displays unsuccessful hiding contact message on UI;
endif
endif
endif
stop
@enduml
