@startuml
start
:User executes hide contact command;
:MyCRM parses user inputs;
while () is ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful hide contact Message on UI;
endwhile ([Valid Input])
:Gets contact to be hidden with index provided;
if () then ([Contact is not hidden])
:Hide the specific contact from MyCRM;
:Displays successful hiding contact message on UI;
else ([Contact is hidden]))
:Throws CommandException;
:Displays unsuccessful hiding contact message on UI;
endif
stop
@enduml
