@startuml
start
:User executes list contact command;
:MyCRM parses user inputs;
if () then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful listing contact message on UI;
else ([Valid Input])
:Gets keyword for predicate of listContact;
if () then ([predicate "-a"])
:Shows all contacts in the list including hidden ones ;
else ([no predicate])
:Shows not hidden contacts in the list;
endif;
:Displays successful listing contact message on UI;
endif
stop
@enduml
