@startuml
start
:User executes undo hide contact command;
:MyCRM parses user inputs;
if () then ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful undoing hiding contact message on UI;
else ([Valid Input])
if () then ([Invalid Index])
    :Throws CommandException;
    :Displays unsuccessful undoing hiding contact on UI;
else ([Else])
:Gets contact to undo hiding with index provided;
if () then ([Contact is hidden])
:Undo Hiding the specific contact from MyCRM;
:Displays successful undoing hiding contact message on UI;
else ([Contact is not hidden])
:Throws CommandException;
:Displays unsuccessful undoing hiding contact message on UI;
endif
endif
endif
stop
@enduml
