@startuml
start
:User executes add contact command;
:myCRM parses user inputs;
while () is ([InValid Input])
    :Throws ParseException;
    :Displays unsuccessful add contact Message on UI;
endwhile ([Valid Input])
    fork
    :Creates new **Name**;
    fork again
    :(Optional)
    Creates new **Phone**;
    fork again
    : (Optional)
    Creates new **Email**;
    fork again
    : (Optional)
    Creates new **Address**;
    end fork
    :Creates new contact;
    :Stores contact into MyCRM;
    :Displays successful add contact Message on UI;
stop
@enduml