@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyMyCrm <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class MyCrm
Class ReadOnlyMyCrm
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

package Entities {
package Contact #F4F6F6{}
package Product #F4F6F6{}
package Template #F4F6F6{}
package Job #F4F6F6{}
package Mail #F4F6F6{}
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

MyCrm .up.|> ReadOnlyMyCrm

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyMyCrm
ModelManager -left-> "1" MyCrm
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

MyCrm *--> Entities
ModelManager -[hidden]-> Entities
ModelManager --> Entities
note top of Entities: Every package within\nEntities is associated with\nMyCrm and ModelManager


Job --> "1" Product
Job --> "1" Contact

Mail--> "1" Template
Mail --> "1" Job

@enduml
