@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "MyCrm Storage" #F4F6F6{
Interface MyCrmStorage <<Interface>>
Class JsonMyCrmStorage
Class JsonSerializableMyCrm
Class JsonAdaptedContact
Class JsonAdaptedTag
Class JsonAdaptedJob
Class JsonAdaptedProduct
Class JsonAdaptedTemplate
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" MyCrmStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> MyCrmStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonMyCrmStorage .up.|> MyCrmStorage
JsonMyCrmStorage ..> JsonSerializableMyCrm
JsonSerializableMyCrm --> "*" JsonAdaptedContact
JsonAdaptedContact --> "*" JsonAdaptedTag
JsonSerializableMyCrm --> "*" JsonAdaptedJob
JsonSerializableMyCrm --> "*" JsonAdaptedProduct
JsonSerializableMyCrm --> "*" JsonAdaptedTemplate
@enduml
