@startuml
start
:User executes add template command;
:MyCRM parses user inputs;
if () then ([Invalid inputs])
    :Throws ParseException;
    :Displays unsuccessful add template on UI;
else ([Valid inputs])
    :Creates new template;
    if () then ([Duplicate template])
        :Throws CommandException;
        :Displays unsuccessful add template on UI;
    else ([Else])
        :Stores template into MyCRM;
        :Displays successful add template on UI;
    endif
endif
stop

@enduml
