@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MyCrmParser" as MyCrmParser LOGIC_COLOR
participant ":EditTemplateCommandParser" as EditTemplateCommandParser LOGIC_COLOR
participant "toEdit:EditTemplateCommand" as EditTemplateCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "editTemplateDescriptor:EditTemplateDescriptor" as EditTemplateDescriptor MODEL_COLOR
end box
[-> LogicManager : execute("editTemplate 1 s/Completed b/Order...")
activate LogicManager

group sd parse edit template
LogicManager -> MyCrmParser : parseCommand("editTemplate 1 s/Completed b/Order...")
activate MyCrmParser

create EditTemplateCommandParser
MyCrmParser -> EditTemplateCommandParser
activate EditTemplateCommandParser

EditTemplateCommandParser --> MyCrmParser
deactivate EditTemplateCommandParser

MyCrmParser -> EditTemplateCommandParser : parse("1 s/Completed b/Order...")
activate EditTemplateCommandParser

create EditTemplateDescriptor
EditTemplateCommandParser -> EditTemplateDescriptor
activate EditTemplateDescriptor
EditTemplateDescriptor --> EditTemplateCommandParser : editTemplateDescriptor
deactivate EditTemplateDescriptor

EditTemplateCommandParser -> EditTemplateDescriptor : setSubject("Completed")

EditTemplateCommandParser -> EditTemplateDescriptor : setBody("Order...)

create EditTemplateCommand
EditTemplateCommandParser -> EditTemplateCommand : 1, editTemplateDescriptor
activate EditTemplateCommand

EditTemplateCommand --> EditTemplateCommandParser : toEdit
deactivate EditTemplateCommand

EditTemplateCommandParser --> MyCrmParser : toEdit
deactivate EditTemplateCommandParser

'Hidden arrow to position destroy marker below the end of the activation bar.
EditTemplateCommandParser -[hidden]-> MyCrmParser
destroy EditTemplateCommandParser

MyCrmParser --> LogicManager : toEdit
deactivate MyCrmParser
end

deactivate LogicManager
@enduml
