@startuml
start
:User executes edit template command;
:MyCRM parses user inputs;
if () then ([Invalid inputs])
    :Throws ParseException;
    :Displays unsuccessful edited template on UI;
else ([Valid inputs])
    if () then ([Index out of range])
        :Throws CommandException;
        :Displays unsuccessful edit template on UI;
    else ([Else])
        :Gets specified template;
        :Creates edited template;
        if () then ([Duplicate template])
            :Throws CommandException;
            :Displays unsuccessful edit template on UI;
        else ([Else])
            :Replaces specified template with edited template;
            :Displays successful edit template on UI;
        endif
    endif
endif
stop

@enduml
