@startuml
start
:User executes find template command;
:MyCRM parses user inputs;
if () then ([Invalid inputs])
    :Throws ParseException;
    :Displays unsuccessful find template on UI;
else ([Valid inputs])
    :Creates subject predicate with keywords;
    :Update template list with new predicate;
    :Displays successful find template on UI;
endif
stop
@enduml
