@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "toAdd:AddProductCommand" as AddProductCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":StateManager" as StateManager LOGIC_COLOR
participant "modifiedResult:CommandResult" as CommandResult2 LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("addProduct n/Asus DUAL-GTX1060-O6G t/GPU m/Asus")
activate LogicManager

ref over LogicManager, AddProductCommand : parse user input

LogicManager -> AddProductCommand : execute()
activate AddProductCommand

AddProductCommand -> Model : addProduct(toAdd)

create CommandResult
AddProductCommand -> CommandResult
activate CommandResult

CommandResult --> AddProductCommand : c
deactivate CommandResult

AddProductCommand -> StateManager : handleProduct(toAdd, c)
activate StateManager

create CommandResult2
StateManager -> CommandResult2
activate CommandResult2

CommandResult2 --> StateManager : modifiedResult
deactivate CommandResult2

StateManager --> AddProductCommand : modifiedResult
deactivate StateManager

AddProductCommand --> LogicManager : modifiedResult
deactivate AddProductCommand

AddProductCommand -[hidden]-> LogicManager
destroy AddProductCommand

[<--LogicManager
deactivate LogicManager
@enduml
