@startuml
start
title Activity: edit product
:User executes edit product command;
:MyCRM parses user inputs;
if () then ([Invalid Input])
    :Throws ParseException;
    :Displays error message;
else ([Valid Input])
if () then ([Duplicate product or Index out of range])
    :Throws CommandException;
    :Displays error message;
else ([else])
    :Gets product to be edited;
    :Creates edited product;
    :Replaces specific product with edited product;
    :Updates product references in jobs;
    :Displays successful message;
endif
endif
stop
@enduml
